# Generated by Django 4.2.3 on 2023-07-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('interest', models.TextField(max_length=50)),
                ('companyname', models.CharField(max_length=50)),
                ('biodata', models.FileField(upload_to='partner/pdfs/docx/doc')),
                ('acceptancenote', models.FileField(upload_to='partner/pdfs/docx/doc')),
            ],
        ),
        migrations.DeleteModel(
            name='partner',
        ),
    ]
