# Generated by Django 4.2.3 on 2023-07-26 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrAdmin', '0002_partne_delete_partner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('districts', models.TextField(max_length=100)),
                ('employees', models.TextField(max_length=100)),
                ('project', models.DateTimeField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('description', models.TextField(max_length=100)),
                ('objectives', models.TextField(max_length=100)),
                ('program', models.TextField(max_length=100)),
                ('pam', models.TextField(max_length=100)),
                ('employees', models.TextField(max_length=100)),
                ('startdate', models.DateTimeField(blank=True)),
                ('endperiod', models.DateTimeField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tasks', models.TextField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='partne',
            name='interest',
            field=models.TextField(max_length=100),
        ),
    ]
